[package]
name = "spl-token-2022"
version = "6.0.0"
description = "Solana Program Library Token 2022"
documentation = "https://docs.rs/spl-token-2022"
readme = "README.md"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []
zk-ops = []

[dependencies]
arrayref = "0.3.9"
bytemuck = { version = "1.18.0", features = ["derive"] }
num_enum = { version = "0.7.3", default-features = false }
solana-program = "2.1.0"
spl-discriminator = { version = "0.4.1", features = ["derive"] }
spl-memo = { version = "5.0.0", features = ["no-entrypoint"] }
spl-pod = "0.5.1"
spl-program-error = "0.5.0"
spl-token-group-interface = { version = "0.2.4" }
spl-token-metadata-interface = { version = "0.3.4" }
spl-transfer-hook-interface = { version = "0.6.4" }
spl-type-length-value = { version = "0.7.0" }
thiserror = "1.0.63"

[dev-dependencies]
solana-sdk = "2.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[package.metadata.solana]
program-id = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
