[package]
name = "spl-token-2022"
version = "6.0.0"
description = "SPL Token 2022 Program"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/token-2022"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
custom-heap = []
custom-panic = []
frozen-abi = []
default = []
zk-ops = []

[dependencies]
arrayref = "0.3.6"
bytemuck = { version = "1.18.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.2"
solana-program = { git = "https://github.com/solana-labs/solana.git", rev = "b1e378009ffee4c75965723d3317fccbebcf2524" }
spl-discriminator = { git = "https://github.com/hamkj7hpo/solana-program-library.git", rev = "3c730e545f179fb18b8e0510706ae9019c84974b", package = "spl-discriminator" }
spl-memo = { git = "https://github.com/hamkj7hpo/memo.git", rev = "8b68bff69ad2616c511f58c16e7588e8997c076c", package = "spl-memo", version = "6.0.0" }
spl-pod = { git = "https://github.com/hamkj7hpo/spl-pod.git", rev = "21076d1f65fb52c40f53feaea14b44dc8f0ce8a5", default-features = false }
spl-token-group-interface = { git = "https://github.com/hamkj7hpo/token-group.git", rev = "e99eb2688b28289559084a2d1d0691e76f02de12", package = "spl-token-group-interface" }
spl-token-metadata-interface = { git = "https://github.com/hamkj7hpo/token-metadata.git", rev = "9f2d6e33950635a2934101c2ee36cef62affa4b8", package = "spl-token-metadata-interface" }
spl-transfer-hook-interface = { git = "https://github.com/hamkj7hpo/transfer-hook.git", rev = "a848a0fdcf10d026a328feb798ca0a5e7f03a4c6", package = "spl-transfer-hook-interface" }
spl-type-length-value = { git = "https://github.com/hamkj7hpo/spl-type-length-value.git", rev = "f88be2a2480bae07e18f2bf5092cc7dea1743d7e", package = "spl-type-length-value" }
spl-tlv-account-resolution = { git = "https://github.com/hamkj7hpo/spl-type-length-value.git", rev = "f88be2a2480bae07e18f2bf5092cc7dea1743d7e", package = "spl-tlv-account-resolution" }
solana-zk-sdk = { git = "https://github.com/hamkj7hpo/zk-elgamal-proof.git", rev = "23b6956ab6b9b8a2797540e41023f51ee8c2d491", package = "solana-zk-sdk" }
thiserror = "1.0.38"

[dev-dependencies]
solana-program-test = { git = "https://github.com/solana-labs/solana.git", rev = "b1e378009ffee4c75965723d3317fccbebcf2524" }
solana-sdk = { git = "https://github.com/solana-labs/solana.git", rev = "b1e378009ffee4c75965723d3317fccbebcf2524" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
